object Version{
    const val coroutines = "1.6.3"
    const val core_testing = "2.1.0"
    const val mockito_inline = "4.6.0"
    const val mockito_kotlin = "2.2.0"
    const val core_ktx = "1.7.0"
    const val appcompat = "1.5.0"
    const val material = "1.6.1"
    const val constraint_layout = "2.1.4"
    const val test_ext = "1.1.3"
    const val espresso_core = "3.3.0"
    const val lifecycle = "2.5.1"
    const val activity_ktx = "1.5.1"
    const val barista = "4.2.0"
    const val runner = "1.4.0"
    const val hamcrest = "2.2"
    const val test_rules = "1.4.0"
    const val idling_resource = "1.0.0"
    const val room = "2.4.3"
    const val navigation = "2.5.1"
    const val koin = "3.2.0"
    const val truth = "1.1.3"
}

object Deps{
    const val coroutines_core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Version.coroutines}"
    const val coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Version.coroutines}"
    const val core_testing = "androidx.arch.core:core-testing:${Version.core_testing}"
    const val mockito_inline = "org.mockito:mockito-inline:${Version.mockito_inline}"
    const val mockito_kotlin = "com.nhaarman.mockitokotlin2:mockito-kotlin:${Version.mockito_kotlin}"
    const val core_ktx = "androidx.core:core-ktx:${Version.core_ktx}"
    const val appcompat = "androidx.appcompat:appcompat:${Version.appcompat}"
    const val material = "com.google.android.material:material:${Version.material}"
    const val constraint_layout = "androidx.constraintlayout:constraintlayout:${Version.constraint_layout}"
    const val test_ext = "androidx.test.ext:junit:${Version.test_ext}"
    const val espresso_core = "androidx.test.espresso:espresso-core:${Version.espresso_core}"
    const val livedata = "androidx.lifecycle:lifecycle-livedata-ktx:${Version.lifecycle}"
//    const val view_model = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.lifecycle}"
    const val coroutines_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Version.coroutines}"
    const val activity_ktx = "androidx.activity:activity-ktx:${Version.activity_ktx}"
    const val navigation_fragment = "androidx.navigation:navigation-fragment-ktx:${Version.navigation}"
    const val navigation_ui = "androidx.navigation:navigation-ui-ktx:${Version.navigation}"
    const val barista = "com.adevinta.android:barista:${Version.barista}"
    const val runner = "androidx.test:runner:${Version.runner}"
    const val hamcrest = "org.hamcrest:hamcrest:${Version.hamcrest}"
    const val test_rules = "androidx.test:rules:${Version.test_rules}"
    const val idling_resource = "com.jakewharton.espresso:okhttp3-idling-resource:${Version.idling_resource}"
    const val koin = "io.insert-koin:koin-android:${Version.koin}"
    const val truth = "com.google.truth:truth:${Version.truth}"
    const val room_runtime = "androidx.room:room-runtime:${Version.room}"
    const val room_ktx = "androidx.room:room-ktx:${Version.room}"
    const val room_compiler = "androidx.room:room-compiler:${Version.room}"
}